### ISSUE TITLE
Disable allDay events

### ISSUE THREAD

**Issue by AlessandroAnnini** [intljusticemission/react-big-calendar#1403]
How can I disable allDay events so that I will not see the first cells on the ui?
I did not found it on the docs nor in other issues.

Thanks

**Comment by michalakjan** [comment]
For now, the only available option is to use css for that

```css
.rbc-allday-cell {
   display: none;
}
```

And as far as I remember there were discussions to create an option for this which IMO would be useful. I've personally had to in 2 different projects hide it using css what isn't the most elegant way

**Comment by michalak111** [comment]
For now, the only available option is to use css for that

```css
.rbc-allday-cell {
   display: none;
}
```

And as far as I remember there were discussions to create an option for this which IMO would be useful. I've personally had to in 2 different projects hide it using css what isn't the most elegant way
