### ISSUE TITLE
Drag and Drop: Dropping on a slot with a pre-existing event

### ISSUE THREAD

**Issue by queicherius** [intljusticemission/react-big-calendar#368]
First off: Thanks for this amazing component, it's been a breeze to work with so far! :1st_place_medal: 

I'm currently having an issue where dragging and dropping an event on a slot with an already existing event shows a "disabled" mouse pointer and does not fire the drop event.

![Gif: Trying to drop on a pre-existing event](http://i.imgur.com/w10PV9c.gif)

However, the whole thing works perfectly when the event is already next to it (because it got passed into `bookings` like that):

![Gif: Drop next to a pre-existing event when already next to it](http://i.imgur.com/rwVdkcZ.gif)

Is there any configuration setting that I am missing?

**Comment by martinnov92** [comment]
Hello, I had  the same issue, you have to tweek CSS's z-index and it will work perfectly. I think all I did was to set z-index on the class with dnd-is-over or something with that class name...

**Comment by queicherius** [comment]
It feels a bit hacky, but this does indeed work:

```css
.rbc-addons-dnd.rbc-addons-dnd-is-dragging .rbc-event {
  z-index: -1;
}

.rbc-today {
  background-color: rgba(234, 246, 255, 0.5);
}
```

Thanks for the headsup! 👍
