### ISSUE TITLE
Touch event selection broken with css property zoom

### ISSUE THREAD

**Issue by pbarbiero** [intljusticemission/react-big-calendar#785]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Touch drag and drop is broken with a zoom property applied to the body tag. Instead of coordinates being calculated properly, the offset is dramatic.

![broken](https://user-images.githubusercontent.com/20247733/38098971-fc91d464-333e-11e8-9110-c777e9f66a00.gif)

#### What's the expected behavior?

![working](https://user-images.githubusercontent.com/20247733/38098984-0326cf96-333f-11e8-9935-751df4764d0b.gif)

Can be reproduced with:
```css
@media (max-width: 980px)
body {
    zoom: 200%;
    height: auto;
}
```
